import { Patient, Appointment, AdmissionDataPoint, DashboardStats } from "./types";

export const patients: Patient[] = [
  {
    id: "P001",
    name: "Sarah Mitchell",
    age: 54,
    gender: "Female",
    bloodType: "A+",
    condition: "Type 2 Diabetes",
    status: "Stable",
    admittedDate: "2026-04-08",
    doctor: "Dr. James Carter",
    department: "Endocrinology",
    phone: "+1 (555) 201-4832",
    email: "s.mitchell@email.com",
    allergies: ["Penicillin", "Sulfa drugs"],
    medications: [
      { id: "M001", patientId: "P001", name: "Metformin", dosage: "500mg", frequency: "Twice daily", startDate: "2026-04-08" },
      { id: "M002", patientId: "P001", name: "Lisinopril", dosage: "10mg", frequency: "Once daily", startDate: "2026-04-08" },
    ],
    diagnosisHistory: [
      { date: "2026-04-08", diagnosis: "Type 2 Diabetes - Moderate", doctor: "Dr. James Carter", notes: "HbA1c at 8.2%, initiating Metformin therapy." },
      { date: "2026-03-15", diagnosis: "Hypertension", doctor: "Dr. James Carter", notes: "BP 145/90, added Lisinopril." },
    ],
  },
  {
    id: "P002",
    name: "Robert Chen",
    age: 67,
    gender: "Male",
    bloodType: "O+",
    condition: "Acute Myocardial Infarction",
    status: "Critical",
    admittedDate: "2026-04-14",
    doctor: "Dr. Priya Sharma",
    department: "Cardiology",
    phone: "+1 (555) 302-7741",
    email: "r.chen@email.com",
    allergies: ["Aspirin", "Ibuprofen", "Latex"],
    medications: [
      { id: "M003", patientId: "P002", name: "Heparin", dosage: "5000 IU", frequency: "4 hrs IV", startDate: "2026-04-14" },
      { id: "M004", patientId: "P002", name: "Nitroglycerin", dosage: "0.4mg", frequency: "PRN sublingual", startDate: "2026-04-14" },
      { id: "M005", patientId: "P002", name: "Atorvastatin", dosage: "80mg", frequency: "Once daily", startDate: "2026-04-14" },
    ],
    diagnosisHistory: [
      { date: "2026-04-14", diagnosis: "Acute STEMI", doctor: "Dr. Priya Sharma", notes: "Emergency angioplasty performed. LAD stent placed successfully." },
      { date: "2026-04-14", diagnosis: "Cardiogenic Shock Risk", doctor: "Dr. Priya Sharma", notes: "EF 35%, monitoring closely in ICU." },
    ],
  },
  {
    id: "P003",
    name: "Emily Rodriguez",
    age: 29,
    gender: "Female",
    bloodType: "B+",
    condition: "Appendicitis - Post Surgery",
    status: "Stable",
    admittedDate: "2026-04-12",
    doctor: "Dr. Alan Brooks",
    department: "General Surgery",
    phone: "+1 (555) 408-9213",
    email: "e.rodriguez@email.com",
    allergies: ["Codeine"],
    medications: [
      { id: "M006", patientId: "P003", name: "Amoxicillin", dosage: "500mg", frequency: "Three times daily", startDate: "2026-04-12" },
      { id: "M007", patientId: "P003", name: "Paracetamol", dosage: "1000mg", frequency: "Every 6 hours PRN", startDate: "2026-04-12" },
    ],
    diagnosisHistory: [
      { date: "2026-04-12", diagnosis: "Acute Appendicitis", doctor: "Dr. Alan Brooks", notes: "Laparoscopic appendectomy completed. No complications." },
      { date: "2026-04-13", diagnosis: "Post-Op Recovery", doctor: "Dr. Alan Brooks", notes: "Wound healing well. Tolerating oral diet." },
    ],
  },
  {
    id: "P004",
    name: "Michael Thompson",
    age: 72,
    gender: "Male",
    bloodType: "AB+",
    condition: "COPD Exacerbation",
    status: "Monitoring",
    admittedDate: "2026-04-10",
    doctor: "Dr. Natalie Wong",
    department: "Pulmonology",
    phone: "+1 (555) 512-6677",
    email: "m.thompson@email.com",
    allergies: ["NSAIDs"],
    medications: [
      { id: "M008", patientId: "P004", name: "Salbutamol Inhaler", dosage: "2 puffs", frequency: "Every 4 hours", startDate: "2026-04-10" },
      { id: "M009", patientId: "P004", name: "Prednisolone", dosage: "40mg", frequency: "Once daily", startDate: "2026-04-10" },
      { id: "M010", patientId: "P004", name: "Ipratropium", dosage: "500mcg", frequency: "Three times daily via nebulizer", startDate: "2026-04-10" },
    ],
    diagnosisHistory: [
      { date: "2026-04-10", diagnosis: "COPD Exacerbation - Moderate", doctor: "Dr. Natalie Wong", notes: "SpO2 88% on admission. Started O2 at 2L/min." },
      { date: "2026-04-12", diagnosis: "Improving Respiratory Function", doctor: "Dr. Natalie Wong", notes: "SpO2 94% on room air. Reducing steroids." },
    ],
  },
  {
    id: "P005",
    name: "Lisa Patel",
    age: 45,
    gender: "Female",
    bloodType: "O-",
    condition: "Fractured Femur",
    status: "Stable",
    admittedDate: "2026-04-09",
    doctor: "Dr. Kevin Mills",
    department: "Orthopedics",
    phone: "+1 (555) 617-3342",
    email: "l.patel@email.com",
    allergies: ["Morphine"],
    medications: [
      { id: "M011", patientId: "P005", name: "Oxycodone", dosage: "5mg", frequency: "Every 6 hours PRN", startDate: "2026-04-09" },
      { id: "M012", patientId: "P005", name: "Enoxaparin", dosage: "40mg", frequency: "Once daily subcutaneous", startDate: "2026-04-09" },
    ],
    diagnosisHistory: [
      { date: "2026-04-09", diagnosis: "Closed Femur Fracture - Left", doctor: "Dr. Kevin Mills", notes: "ORIF surgery completed. Good alignment on post-op X-ray." },
      { date: "2026-04-13", diagnosis: "Physical Therapy Initiated", doctor: "Dr. Kevin Mills", notes: "Partial weight bearing with walker. PT sessions 2x daily." },
    ],
  },
  {
    id: "P006",
    name: "James Wilson",
    age: 38,
    gender: "Male",
    bloodType: "A-",
    condition: "Acute Pancreatitis",
    status: "Monitoring",
    admittedDate: "2026-04-13",
    doctor: "Dr. Susan Lee",
    department: "Gastroenterology",
    phone: "+1 (555) 714-8810",
    email: "j.wilson@email.com",
    allergies: ["Contrast dye"],
    medications: [
      { id: "M013", patientId: "P006", name: "Morphine", dosage: "4mg", frequency: "Every 4 hours IV PRN", startDate: "2026-04-13" },
      { id: "M014", patientId: "P006", name: "Ondansetron", dosage: "4mg", frequency: "Every 8 hours IV", startDate: "2026-04-13" },
    ],
    diagnosisHistory: [
      { date: "2026-04-13", diagnosis: "Acute Pancreatitis - Moderate", doctor: "Dr. Susan Lee", notes: "Lipase 1200 U/L. NPO, IV fluids initiated." },
    ],
  },
  {
    id: "P007",
    name: "Amelia Johnson",
    age: 61,
    gender: "Female",
    bloodType: "B-",
    condition: "Ischemic Stroke",
    status: "Critical",
    admittedDate: "2026-04-15",
    doctor: "Dr. Priya Sharma",
    department: "Neurology",
    phone: "+1 (555) 819-5530",
    email: "a.johnson@email.com",
    allergies: ["Warfarin sensitivity"],
    medications: [
      { id: "M015", patientId: "P007", name: "tPA (Alteplase)", dosage: "0.9 mg/kg", frequency: "One-time IV bolus", startDate: "2026-04-15" },
      { id: "M016", patientId: "P007", name: "Aspirin", dosage: "325mg", frequency: "Once daily", startDate: "2026-04-15" },
    ],
    diagnosisHistory: [
      { date: "2026-04-15", diagnosis: "Acute Ischemic Stroke - Left MCA", doctor: "Dr. Priya Sharma", notes: "tPA administered within window. CT shows no hemorrhage. Stroke team activated." },
    ],
  },
  {
    id: "P008",
    name: "David Kim",
    age: 50,
    gender: "Male",
    bloodType: "O+",
    condition: "Kidney Stones",
    status: "Stable",
    admittedDate: "2026-04-11",
    doctor: "Dr. Mark Evans",
    department: "Urology",
    phone: "+1 (555) 920-4471",
    email: "d.kim@email.com",
    allergies: [],
    medications: [
      { id: "M017", patientId: "P008", name: "Tamsulosin", dosage: "0.4mg", frequency: "Once daily", startDate: "2026-04-11" },
      { id: "M018", patientId: "P008", name: "Ketorolac", dosage: "30mg", frequency: "Every 6 hours IV PRN", startDate: "2026-04-11" },
    ],
    diagnosisHistory: [
      { date: "2026-04-11", diagnosis: "Nephrolithiasis - Right Ureter", doctor: "Dr. Mark Evans", notes: "6mm stone at UVJ. ESWL scheduled." },
      { date: "2026-04-13", diagnosis: "Post ESWL", doctor: "Dr. Mark Evans", notes: "Stone fragmenting. Urine straining in place." },
    ],
  },
  {
    id: "P009",
    name: "Sophia Turner",
    age: 33,
    gender: "Female",
    bloodType: "AB-",
    condition: "Pneumonia",
    status: "Monitoring",
    admittedDate: "2026-04-12",
    doctor: "Dr. Natalie Wong",
    department: "Pulmonology",
    phone: "+1 (555) 103-6621",
    email: "s.turner@email.com",
    allergies: ["Azithromycin"],
    medications: [
      { id: "M019", patientId: "P009", name: "Ceftriaxone", dosage: "1g", frequency: "Once daily IV", startDate: "2026-04-12" },
      { id: "M020", patientId: "P009", name: "Doxycycline", dosage: "100mg", frequency: "Twice daily oral", startDate: "2026-04-12" },
    ],
    diagnosisHistory: [
      { date: "2026-04-12", diagnosis: "Community-Acquired Pneumonia", doctor: "Dr. Natalie Wong", notes: "RLL consolidation on CXR. Started dual antibiotic therapy." },
    ],
  },
  {
    id: "P010",
    name: "Charles Brown",
    age: 78,
    gender: "Male",
    bloodType: "A+",
    condition: "Hip Replacement Recovery",
    status: "Stable",
    admittedDate: "2026-04-07",
    doctor: "Dr. Kevin Mills",
    department: "Orthopedics",
    phone: "+1 (555) 204-9903",
    email: "c.brown@email.com",
    allergies: ["Latex"],
    medications: [
      { id: "M021", patientId: "P010", name: "Warfarin", dosage: "5mg", frequency: "Once daily", startDate: "2026-04-07" },
      { id: "M022", patientId: "P010", name: "Celecoxib", dosage: "200mg", frequency: "Twice daily", startDate: "2026-04-07" },
    ],
    diagnosisHistory: [
      { date: "2026-04-07", diagnosis: "Right Total Hip Arthroplasty", doctor: "Dr. Kevin Mills", notes: "Successful THA. Estimated discharge: 3-4 days." },
      { date: "2026-04-10", diagnosis: "DVT Prophylaxis", doctor: "Dr. Kevin Mills", notes: "Warfarin initiated. INR monitoring daily." },
      { date: "2026-04-14", diagnosis: "Progressing Well", doctor: "Dr. Kevin Mills", notes: "Full weight bearing achieved. Discharge planning started." },
    ],
  },
  {
    id: "P011",
    name: "Olivia Harris",
    age: 42,
    gender: "Female",
    bloodType: "B+",
    condition: "Sepsis - UTI Origin",
    status: "Critical",
    admittedDate: "2026-04-15",
    doctor: "Dr. James Carter",
    department: "Intensive Care",
    phone: "+1 (555) 305-7724",
    email: "o.harris@email.com",
    allergies: ["Cephalosporins", "Sulfa drugs"],
    medications: [
      { id: "M023", patientId: "P011", name: "Piperacillin-Tazobactam", dosage: "4.5g", frequency: "Every 6 hours IV", startDate: "2026-04-15" },
      { id: "M024", patientId: "P011", name: "Norepinephrine", dosage: "0.1 mcg/kg/min", frequency: "Continuous IV infusion", startDate: "2026-04-15" },
    ],
    diagnosisHistory: [
      { date: "2026-04-15", diagnosis: "Septic Shock - UTI Source", doctor: "Dr. James Carter", notes: "MAP <65 despite fluids. Vasopressors initiated. ICU admission." },
    ],
  },
  {
    id: "P012",
    name: "Ethan Foster",
    age: 19,
    gender: "Male",
    bloodType: "O-",
    condition: "Asthma Attack",
    status: "Stable",
    admittedDate: "2026-04-14",
    doctor: "Dr. Natalie Wong",
    department: "Emergency",
    phone: "+1 (555) 406-1182",
    email: "e.foster@email.com",
    allergies: ["Aspirin", "NSAIDs"],
    medications: [
      { id: "M025", patientId: "P012", name: "Salbutamol", dosage: "2.5mg", frequency: "Nebulization every 20min x3", startDate: "2026-04-14" },
      { id: "M026", patientId: "P012", name: "Methylprednisolone", dosage: "125mg", frequency: "Once IV", startDate: "2026-04-14" },
    ],
    diagnosisHistory: [
      { date: "2026-04-14", diagnosis: "Acute Severe Asthma", doctor: "Dr. Natalie Wong", notes: "PEFR 40% on arrival. Responded to bronchodilators. Moving from ED to ward." },
    ],
  },
];

export const appointments: Appointment[] = [
  { id: "A001", patientId: "P001", patientName: "Sarah Mitchell", date: "2026-04-15", time: "09:00", department: "Endocrinology", doctor: "Dr. James Carter", type: "Follow-up", status: "In Progress" },
  { id: "A002", patientId: "P004", patientName: "Michael Thompson", date: "2026-04-15", time: "09:30", department: "Pulmonology", doctor: "Dr. Natalie Wong", type: "Consultation", status: "Scheduled" },
  { id: "A003", patientId: "P003", patientName: "Emily Rodriguez", date: "2026-04-15", time: "10:00", department: "General Surgery", doctor: "Dr. Alan Brooks", type: "Follow-up", status: "Scheduled" },
  { id: "A004", patientId: "P002", patientName: "Robert Chen", date: "2026-04-15", time: "10:30", department: "Cardiology", doctor: "Dr. Priya Sharma", type: "Emergency", status: "Completed" },
  { id: "A005", patientId: "P005", patientName: "Lisa Patel", date: "2026-04-15", time: "11:00", department: "Orthopedics", doctor: "Dr. Kevin Mills", type: "Routine Checkup", status: "Scheduled" },
  { id: "A006", patientId: "P008", patientName: "David Kim", date: "2026-04-15", time: "11:30", department: "Urology", doctor: "Dr. Mark Evans", type: "Follow-up", status: "Scheduled" },
  { id: "A007", patientId: "P010", patientName: "Charles Brown", date: "2026-04-15", time: "14:00", department: "Orthopedics", doctor: "Dr. Kevin Mills", type: "Routine Checkup", status: "Scheduled" },
  { id: "A008", patientId: "P009", patientName: "Sophia Turner", date: "2026-04-15", time: "14:30", department: "Pulmonology", doctor: "Dr. Natalie Wong", type: "Follow-up", status: "Scheduled" },
  { id: "A009", patientId: "P012", patientName: "Ethan Foster", date: "2026-04-16", time: "09:00", department: "Emergency", doctor: "Dr. Natalie Wong", type: "Follow-up", status: "Scheduled" },
  { id: "A010", patientId: "P006", patientName: "James Wilson", date: "2026-04-16", time: "10:00", department: "Gastroenterology", doctor: "Dr. Susan Lee", type: "Consultation", status: "Scheduled" },
  { id: "A011", patientId: "P001", patientName: "Sarah Mitchell", date: "2026-04-17", time: "09:00", department: "Endocrinology", doctor: "Dr. James Carter", type: "Routine Checkup", status: "Scheduled" },
  { id: "A012", patientId: "P007", patientName: "Amelia Johnson", date: "2026-04-17", time: "11:00", department: "Neurology", doctor: "Dr. Priya Sharma", type: "Follow-up", status: "Scheduled" },
  { id: "A013", patientId: "P011", patientName: "Olivia Harris", date: "2026-04-18", time: "08:00", department: "Intensive Care", doctor: "Dr. James Carter", type: "Consultation", status: "Scheduled" },
  { id: "A014", patientId: "P005", patientName: "Lisa Patel", date: "2026-04-18", time: "15:00", department: "Orthopedics", doctor: "Dr. Kevin Mills", type: "Follow-up", status: "Scheduled" },
  { id: "A015", patientId: "P004", patientName: "Michael Thompson", date: "2026-04-19", time: "10:00", department: "Pulmonology", doctor: "Dr. Natalie Wong", type: "Follow-up", status: "Scheduled" },
];

export const admissionTrend: AdmissionDataPoint[] = [
  { day: "Apr 9",  admissions: 8,  discharges: 5 },
  { day: "Apr 10", admissions: 11, discharges: 9 },
  { day: "Apr 11", admissions: 7,  discharges: 6 },
  { day: "Apr 12", admissions: 14, discharges: 10 },
  { day: "Apr 13", admissions: 9,  discharges: 12 },
  { day: "Apr 14", admissions: 13, discharges: 8 },
  { day: "Apr 15", admissions: 6,  discharges: 7 },
];

export const dashboardStats: DashboardStats = {
  totalPatients: 247,
  todayAppointments: 18,
  criticalAlerts: 3,
  dischargedToday: 7,
  weeklyAdmissions: 68,
  avgStayDays: 4.2,
};
